// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiLzNJg3td1RHuKFgQ3LWb1x4ymWK_jzI',
    appId: '1:592003571370:web:43274fd334b77a419ffad3',
    messagingSenderId: '592003571370',
    projectId: 'test-1f643',
    authDomain: 'test-1f643.firebaseapp.com',
    storageBucket: 'test-1f643.firebasestorage.app',
    measurementId: 'G-9BYCRD6YSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JKIeVPySi5mQcsJkpFw_lu7O-JAjp9I',
    appId: '1:592003571370:android:277fb64150f3e40a9ffad3',
    messagingSenderId: '592003571370',
    projectId: 'test-1f643',
    storageBucket: 'test-1f643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5QNkxkYGGo4O4IsZF7JWIsrPQ0osKlk',
    appId: '1:592003571370:ios:6e06c4faaf0c24ac9ffad3',
    messagingSenderId: '592003571370',
    projectId: 'test-1f643',
    storageBucket: 'test-1f643.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk5QNkxkYGGo4O4IsZF7JWIsrPQ0osKlk',
    appId: '1:592003571370:ios:6e06c4faaf0c24ac9ffad3',
    messagingSenderId: '592003571370',
    projectId: 'test-1f643',
    storageBucket: 'test-1f643.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiLzNJg3td1RHuKFgQ3LWb1x4ymWK_jzI',
    appId: '1:592003571370:web:34a00e61bfe9080d9ffad3',
    messagingSenderId: '592003571370',
    projectId: 'test-1f643',
    authDomain: 'test-1f643.firebaseapp.com',
    storageBucket: 'test-1f643.firebasestorage.app',
    measurementId: 'G-Y2THHBL9J0',
  );
}
